# Generated by Django 2.2.2 on 2019-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190606_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgtxtpair',
            name='choice1_src',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgtxtpair',
            name='choice2_src',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
