# Generated by Django 2.2.2 on 2019-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190606_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='userid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
